add_pellet:
  name: Aggiungi sacchi di pellet
  description: Aggiunge sacchi di pellet alla scorta totale
  fields:
    quantity:
      name: Quantità
      description: Numero di sacchi da aggiungere
      required: true
      example: 10

remove_pellet:
  name: Scala sacchi di pellet
  description: Scala sacchi di pellet dalla scorta totale
  fields:
    quantity:
      name: Quantità
      description: Numero di sacchi da scalare
      required: true
      example: 5